"""metadata linked to file, nullable tags

Revision ID: 22d226584143
Revises: 3453aa77e602
Create Date: 2026-07-09 14:53:31.550773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '22d226584143'
down_revision: Union[str, Sequence[str], None] = '3453aa77e602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('idFile', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False))
    op.alter_column('metadata', 'songName',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('metadata', 'songArtist',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('metadata', 'duration',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('metadata', 'albumName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('metadata', 'publishDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'metadata', 'files', ['idFile'], ['idFile'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metadata', type_='foreignkey')
    op.alter_column('metadata', 'publishDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('metadata', 'albumName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('metadata', 'duration',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('metadata', 'songArtist',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('metadata', 'songName',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_column('metadata', 'idFile')
    # ### end Alembic commands ###
