"""initial schema

Revision ID: 3453aa77e602
Revises: 
Create Date: 2026-07-09 11:06:21.614792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3453aa77e602'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('idMetadata', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('songName', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('songArtist', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('albumName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('publishDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idMetadata')
    )
    op.create_table('playlists',
    sa.Column('idPlaylist', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idPlaylist')
    )
    op.create_table('users',
    sa.Column('idUser', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('passwd', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idUser')
    )
    op.create_table('files',
    sa.Column('idFile', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('ext', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('idFile')
    )
    op.create_table('playlist_files',
    sa.Column('idPlaylist', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('idFile', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.ForeignKeyConstraint(['idFile'], ['files.idFile'], ),
    sa.ForeignKeyConstraint(['idPlaylist'], ['playlists.idPlaylist'], ),
    sa.PrimaryKeyConstraint('idPlaylist', 'idFile')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_files')
    op.drop_table('files')
    op.drop_table('users')
    op.drop_table('playlists')
    op.drop_table('metadata')
    # ### end Alembic commands ###
