"""sharing, cover, email_verified, play history

Revision ID: 9b6a7e432ce9
Revises: 0ef82d728573
Create Date: 2026-07-09 17:32:55.488146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b6a7e432ce9'
down_revision: Union[str, Sequence[str], None] = '0ef82d728573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_events',
    sa.Column('idEvent', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('idUser', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('idFile', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('played_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idFile'], ['files.idFile'], ),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('idEvent')
    )
    op.add_column('files', sa.Column('has_cover', sa.Boolean(), nullable=False))
    op.add_column('playlists', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('playlists', 'is_public')
    op.drop_column('files', 'has_cover')
    op.drop_table('play_events')
    # ### end Alembic commands ###
