"""playlist owner (created_by)

Revision ID: a2619d65d997
Revises: 22d226584143
Create Date: 2026-07-09 15:29:46.858381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2619d65d997'
down_revision: Union[str, Sequence[str], None] = '22d226584143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False))
    op.create_foreign_key(None, 'playlists', 'users', ['created_by'], ['idUser'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'created_by')
    # ### end Alembic commands ###
