"""devices table

Revision ID: ee91fb2bff82
Revises: f1d726b57733
Create Date: 2026-07-09 17:46:52.758057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee91fb2bff82'
down_revision: Union[str, Sequence[str], None] = 'f1d726b57733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('idDevice', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('idUser', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idUser'], ['users.idUser'], ),
    sa.PrimaryKeyConstraint('idDevice')
    )
    op.create_index(op.f('ix_devices_code'), 'devices', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
