"""email unique + playlist_files position

Revision ID: fc7a72f3cd02
Revises: a2619d65d997
Create Date: 2026-07-09 16:54:45.462116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc7a72f3cd02'
down_revision: Union[str, Sequence[str], None] = 'a2619d65d997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_files', sa.Column('position', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('playlist_files', 'position')
    # ### end Alembic commands ###
